# 应用名称
spring:
  main:
    allow-circular-references: true # 允许循环引用
  application:
    name: oaback_server
  redis:
    host: localhost
    database: 0
    port: 6379
  datasource:
    username: root
    password: victorysu1131526
    url: jdbc:mysql://localhost:3306/office_oa?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
server:
   port: 9999


